from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Alphabet import generic_protein
from Bio import SeqIO
import sys

def main(script):

	rec1 = SeqRecord(Seq("MMYQQGCFAGGTVLRLAKDLAENNRGARVLVVCSEITAVTFRGPSETHLDSMVGQALFGD" \
	+"GAGAVIVGSDPDLSVERPLYELVWTGATLLPDSEGAIDGHLREVGLTFHLLKDVPGLISK" \
	+"NIEKSLKEAFTPLGISDWNSTFWIAHPGGPAILDQVEAKLGLKEEKMRATREVLSEYGNM" \
	+"SSAC", generic_protein),
	id="gi|14150838|gb|AAK54648.1|AF376133_1",
	description="chalcone synthase [Cucumis sativus]")

	rec2 = SeqRecord(Seq("YPDYYFRITNREHKAELKEKFQRMCDKSMIKKRYMYLTEEILKENPSMCEYMAPSLDARQ" \
	+"DMVVVEIPKLGKEAAVKAIKEWGQ", generic_protein),
	id="gi|13919613|gb|AAK33142.1|",
	description="chalcone synthase [Fragaria vesca subsp. bracteata]")

	rec3 = SeqRecord(Seq("MVTVEEFRRAQCAEGPATVMAIGTATPSNCVDQSTYPDYYFRITNSEHKVELKEKFKRMC" \
	+"EKSMIKKRYMHLTEEILKENPNICAYMAPSLDARQDIVVVEVPKLGKEAAQKAIKEWGQP" \
	+"KSKITHLVFCTTSGVDMPGCDYQLTKLLGLRPSVKRFMMYQQGCFAGGTVLRMAKDLAEN" \
	+"NKGARVLVVCSEITAVTFRGPNDTHLDSLVGQALFGDGAAAVIIGSDPIPEVERPLFELV" \
	+"SAAQTLLPDSEGAIDGHLREVGLTFHLLKDVPGLISKNIEKSLVEAFQPLGISDWNSLFW" \
	+"IAHPGGPAILDQVELKLGLKQEKLKATRKVLSNYGNMSSACVLFILDEMRKASAKEGLGT" \
	+"TGEGLEWGVLFGFGPGLTVETVVLHSVAT", generic_protein),
	id="gi|13925890|gb|AAK49457.1|",
	description="chalcone synthase [Nicotiana tabacum]")

	my_records = [rec1, rec2, rec3]

	num_seqs = SeqIO.write(my_records, "my_example.fasta", "fasta")
	print '# of sequences: ', num_seqs
	
if __name__ == '__main__':
	main(*sys.argv)